[package]
name = "api-dev"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
tokio = {version = "1", features = ["full"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1"

[dev-dependencies]
anyhow = "1"
httpc-test = "0.1.1"

